apiVersion: v1
kind: Service
metadata:
  name: rtvt-lipsync-service
  labels:
    app: rtvt-lipsync
spec:
  type: NodePort
  selector:
    app: rtvt-lipsync
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
